branches:
  - main
  - next
preset: angular
plugins:
  - path: "@semantic-release/commit-analyzer"
  - path: "@semantic-release/exec"
    prepareCmd: "sh release_package.sh ${nextRelease.version}"
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
  - path: "@semantic-release/release-notes-generator"
  - path: "@semantic-release/github"
    assets:
      - path: "dist/*.whl"
        label: "sample-package-${nextRelease.version}.whl"
      - path: "dist/*.tar.gz"
        label: "sample-package-${nextRelease.version}.tar.gz"
