name: Release
on:
  push:
    branches:
      - main
      - next
jobs:

  release:

    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Semantic Release
        run: |
          npm install -g semantic-release           \
          @semantic-release/changelog               \
          @semantic-release/commit-analyzer         \
          @semantic-release/exec                    \
          @semantic-release/github                  \
          @semantic-release/release-notes-generator

      - name: Run Semantic Release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release