name: Release
on:
  push:
    branches:
      - main
      - next
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:

  release:

    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #------------------------------------------------
      #  -----  check-out repo and set-up python  -----
      #------------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      #------------------------------
      #  -----  Setup Node.js  -----
      #------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      #------------------------------
      #  -----  Install poetry  -----
      #------------------------------
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      #---------------------------------------
      #  -----  Install Semantic Release -----
      #---------------------------------------
      - name: Install Semantic Release
        run: |
          npm install -g semantic-release           \
          @semantic-release/changelog               \
          @semantic-release/commit-analyzer         \
          @semantic-release/exec                    \
          @semantic-release/github                  \
          @semantic-release/release-notes-generator
      #-----------------------------------
      #  -----  Run Semantic Release -----
      #-----------------------------------
      - name: Run Semantic Release
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release